"""add new coloumn status todo

Revision ID: 25898fa03de9
Revises: 70e73eedb22a
Create Date: 2025-12-10 22:05:17.152325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25898fa03de9'
down_revision: Union[str, Sequence[str], None] = '70e73eedb22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'status')
    # ### end Alembic commands ###
